---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: vllm

resources:
- buildconfig.yaml
- deployment.yaml
- imagestream.yaml
- pvc.yaml
- route.yaml
- service.yaml
